LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x16D0
USB_PID = 0x0A0C
USB_PRODUCT = "MT-D21E Rev A"
USB_MANUFACTURER = "MattairTech LLC"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21
